title: "[SDK] <Title>"
labels: ["SDK"]
body:
  - type: markdown
    attributes:
      value: |
        ## Before proceeding, please check these links for SDK help:
        - [TypeScript SDK](https://era.zksync.io/docs/api/js/)
        - [Python SDK](https://era.zksync.io/docs/api/python/getting-started.html)
        - [Java SDK](https://era.zksync.io/docs/api/java/getting-started.html)
        
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - 
        - Testnet
        - Mainnet
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        #### ⚠️ Note
        We are currently updating the Python and Java SDKs. You may encounter errors when trying things out. Apologies for the inconvenience, we will update the documentation in due course.

  - type: checkboxes
    id: sdk-updates-acknowledgement
    attributes:
      label: Acknowledgement
      options:
        - label: I understand that issues are expected with the Python and Java SDK as they are being updated.
    validations:
      required: true
        
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
    validations:
      required: true
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
    validations:
      required: true
  
  - type: textarea
    id: code-example
    attributes:
      label: Code Example
    validations:
      required: true
  
  - type: input
    id: repo-link
    attributes:
      label: Repo Link (Optional)
      description: If applicable, please provide a link to a repo
    validations:
      required: false
